name: filesize
description: A package to get humanized file sizes. Translate raw file size into human readable strings.
author: synw <synwe@yahoo.com>
homepage: https://github.com/synw/filesize

version: 1.0.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  test_cov: ^1.0.1
  pedantic: ^1.11.0